// scripts/bootstrap-grid.ts
//
// Path 3 — the one-shot. Pull the real grid once, enrich it, normalise it,
// cache it whole, dump it to disk, and write it to Convex. Run ONCE at event
// start, server-side. After this, the product never calls JamBase again
// (acceptance criterion 7).
//
// Run:
//   JAMBASE_API_KEY=xxx npx tsx scripts/bootstrap-grid.ts          # live pull
//   npx tsx scripts/bootstrap-grid.ts                              # offline: rebuild
//                                                                    grid.sample.json
//                                                                    from the committed
//                                                                    data/jambase.raw.json
//
// The committed data/grid.sample.json was generated by exactly this pipeline's
// offline branch (toGrid over data/jambase.raw.json). It is "the demo" — treat
// it as the source of truth for the whole team until a live pull replaces it.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  enrichArtist,
  fetchGrid,
  findFestival,
  type ArtistMeta,
  type RawJamBaseEvent,
} from "@/lib/grid/jambase";
import { toGrid } from "@/lib/grid/normalize";
import type { Grid, Stage } from "@/lib/types";

const ROOT = process.cwd();
const RAW_PATH = join(ROOT, "data", "jambase.raw.json");
const GRID_PATH = join(ROOT, "data", "grid.sample.json");

interface BootstrapInput {
  stages: Stage[];
  artistMeta: Record<string, ArtistMeta>;
  events: RawJamBaseEvent[];
}

function readOfflineInput(): BootstrapInput {
  return JSON.parse(readFileSync(RAW_PATH, "utf8")) as BootstrapInput;
}

/** Live pull path: JamBase → raw events → per-artist enrichment. */
async function pullFromJamBase(stages: Stage[]): Promise<BootstrapInput> {
  const { festivalId } = await findFestival("Outside Lands", 2026);
  const events = await fetchGrid(festivalId);

  // Dump the raw payload before parsing, so we can iterate without re-hitting
  // the API and reconcile our types against the JSON actually returned.
  writeFileSync(
    join(ROOT, "data", "jambase.raw.pull.json"),
    JSON.stringify(events, null, 2) + "\n"
  );

  // Enrich each distinct artist once. Batch, rate-limit politely, cache to disk.
  const ids = Array.from(
    new Set(events.map((e) => e.jambaseArtistId).filter((x): x is string => !!x))
  );
  const artistMeta: Record<string, ArtistMeta> = {};
  for (const id of ids) {
    try {
      artistMeta[id] = await enrichArtist(id);
    } catch (err) {
      console.warn(`enrichArtist(${id}) failed, leaving nulls:`, err);
    }
    await sleep(250); // polite rate limit — we run this once, not in a loop
  }
  return { stages, artistMeta, events };
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

/**
 * Write stages + sets into Convex via path 4's mutations. Path 4 owns the schema
 * and the exact mutation name; until that lands this is a guarded stub so the
 * bootstrap is never blocked waiting on another path. Coordinate the real
 * mutation name (expected: `api.grid.bootstrap({ event, stages, sets })`) with
 * path 4 and swap the dynamic import in.
 */
async function writeToConvex(grid: Grid): Promise<void> {
  const url = process.env.CONVEX_URL;
  if (!url) {
    console.log(
      "· Convex write skipped (CONVEX_URL unset). Path 4 not wired yet — " +
        "stages/sets live in data/grid.sample.json for now."
    );
    return;
  }
  try {
    // Deferred to keep this script runnable before path 4 exists.
    // const { ConvexHttpClient } = await import("convex/browser");
    // const client = new ConvexHttpClient(url);
    // await client.mutation("grid:bootstrap", {
    //   event: { festivalId: grid.festivalId, name: grid.eventName, timezone: grid.timezone },
    //   stages: grid.stages,
    //   sets: grid.sets,
    // });
    console.log(
      `· Convex write stubbed for ${grid.stages.length} stages / ${grid.sets.length} sets ` +
        `→ swap in api.grid.bootstrap when path 4 lands.`
    );
  } catch (err) {
    console.warn("Convex write failed (non-fatal for the client cache):", err);
  }
}

async function main() {
  const offline = readOfflineInput();
  const hasKey = !!process.env.JAMBASE_API_KEY;

  const input = hasKey
    ? await pullFromJamBase(offline.stages)
    : (console.log(
        "· No JAMBASE_API_KEY — offline rebuild from data/jambase.raw.json."
      ),
      offline);

  const grid = toGrid(input.events, input.stages, input.artistMeta);

  writeFileSync(GRID_PATH, JSON.stringify(grid, null, 2) + "\n");
  console.log(
    `✓ wrote data/grid.sample.json: ${grid.sets.length} sets across ` +
      `${grid.stages.length} stages (${grid.eventName}, ${grid.timezone}).`
  );

  const withSpotify = grid.sets.filter((s) => s.spotifyId).length;
  const headliners = grid.sets.filter((s) => s.isHeadliner).length;
  console.log(
    `  ${headliners} headliners, ${withSpotify} sets carry a real spotifyId.`
  );
  if (grid.sets.some((s) => s.estimatedAudience == null)) {
    console.log(
      "  NOTE for path 6: estimatedAudience is null (not exposed by JamBase in " +
        "this pull). Degrade rarity gracefully — lean on isHeadliner + slotIndex."
    );
  }

  await writeToConvex(grid);
}

main().catch((err) => {
  console.error("bootstrap-grid failed:", err);
  process.exitCode = 1;
});
